[package]
name = "wgpu_shader_checker"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro=true


[dev-dependencies]
trybuild = "1.0.103"

[dependencies]
naga = "24.0.0"
syn = "2.0.98"
wgpu = "24.0.1"
