name: Rust
on:
  push:
    branches: ["main"]
  pull_request:
    branches: [ "main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build
      - name: Run tests
        run: cargo test -- --nocapture
      - name: Linting
        run: cargo clippy -- -D warnings -D clippy::pedantic -D clippy::nursery
