name: Rust
on:
  push:
    branches: ["master"]
  pull_request:
    branches: [ "master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build
      - name: Run doc tests
        run: cargo test --doc -- --nocapture
      - name: Run lib tests
        run: cargo test --lib -- --nocapture
      - name: Linting
        run: cargo clippy -- -D warnings -D clippy::pedantic -D clippy::nursery
